<a href="https://colab.research.google.com/github/nickfuryavg/Deep-Learning-Basics/blob/main/neutral_network_in_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## neutral network in regression Analysis using forward and backward propagation

In [ ]:
import numpy as np
import pandas as pd
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [ ]:
import numpy as np

# Initialize weights
# Layer 1: Input to Hidden Layer (2 input features, 2 neurons in the hidden layer)
W1 = np.full((2, 2), 0.1)  # Creates a 2x2 matrix filled with 0.1

# Layer 2: Hidden Layer to Output Layer (2 neurons in the hidden layer, 1 output neuron)
W2 = np.full((2, 1), 0.1)  # Creates a 2x1 matrix filled with 0.1

print("Initial weights from Input to Hidden Layer (W1):")
print(W1)
print("Initial weights from Hidden to Output Layer (W2):")
print(W2)


Initial weights from Input to Hidden Layer (W1):
[[0.1 0.1]
 [0.1 0.1]]
Initial weights from Hidden to Output Layer (W2):
[[0.1]
 [0.1]]


In [ ]:
import numpy as np

# Initialize weights
# Layer 1: Input to Hidden Layer (2 input features, 2 neurons in the hidden layer)
W1 = np.full((2, 2), 0.1)

# Layer 2: Hidden Layer to Output Layer (2 neurons in the hidden layer, 1 output neuron)
W2 = np.full((2, 1), 0.1)

# Initialize biases
# Biases for Hidden Layer (2 neurons in the hidden layer)
b1 = np.zeros(2)

# Biases for Output Layer (1 output neuron)
b2 = np.zeros(1)

print("Initial weights from Input to Hidden Layer (W1):")
print(W1)
print("Initial weights from Hidden to Output Layer (W2):")
print(W2)
print("Initial biases for Hidden Layer (b1):")
print(b1)
print("Initial biases for Output Layer (b2):")
print(b2)


Initial weights from Input to Hidden Layer (W1):
[[0.1 0.1]
 [0.1 0.1]]
Initial weights from Hidden to Output Layer (W2):
[[0.1]
 [0.1]]
Initial biases for Hidden Layer (b1):
[0. 0.]
Initial biases for Output Layer (b2):
[0.]


In [ ]:
import numpy as np
import pandas as pd

# Define a linear activation function
def linear(x):
    return x

# Initialize weights
# Layer 1: Input to Hidden Layer (2 input features, 2 neurons in the hidden layer)
W1 = np.full((2, 2), 0.1)

# Layer 2: Hidden Layer to Output Layer (2 neurons in the hidden layer, 1 output neuron)
W2 = np.full((2, 1), 0.1)

# Initialize biases
# Biases for Hidden Layer (2 neurons)
b1 = np.zeros(2)

# Biases for Output Layer (1 output neuron)
b2 = np.zeros(1)

# Create the DataFrame
df = pd.DataFrame([[8, 8, 4], [7, 9, 5], [6, 10, 6], [5, 12, 7]], columns=['cgpa', 'profile_score', 'lpa'])

# Prepare input data (only the first two columns are features)
X = df[['cgpa', 'profile_score']].values

# Forward propagation function with linear activation and tracking each layer's output
def forward_pass_track(X):
    # From input layer to hidden layer
    Z1 = np.dot(X, W1) + b1  # Linear combination: W1*X + b1
    A1 = linear(Z1)  # Linear activation in hidden layer

    # From hidden layer to output layer
    Z2 = np.dot(A1, W2) + b2  # Linear combination: W2*A1 + b2
    A2 = linear(Z2)  # Linear activation in output layer

    return A1, A2  # Returning outputs from each layer

# Perform forward pass and get outputs from each layer
hidden_output, final_output = forward_pass_track(X)

print("Output from Hidden Layer:")
print(hidden_output)
print("Final Network Output:")
print(final_output)


Output from Hidden Layer:
[[1.6 1.6]
 [1.6 1.6]
 [1.6 1.6]
 [1.7 1.7]]
Final Network Output:
[[0.32]
 [0.32]
 [0.32]
 [0.34]]


In [ ]:
import numpy as np
import pandas as pd

# Define a linear activation function
def linear(x):
    return x

# Mean Squared Error Loss function
def mse_loss(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

# Initialize weights
W1 = np.full((2, 2), 0.1)  # Input to Hidden Layer
W2 = np.full((2, 1), 0.1)  # Hidden to Output Layer

# Initialize biases
b1 = np.zeros(2)  # Biases for Hidden Layer
b2 = np.zeros(1)  # Bias for Output Layer

# Create the DataFrame
df = pd.DataFrame([[8, 8, 4], [7, 9, 5], [6, 10, 6], [5, 12, 7]], columns=['cgpa', 'profile_score', 'lpa'])
X = df[['cgpa', 'profile_score']].values
Y = df['lpa'].values.reshape(-1, 1)

# Learning rate
learning_rate = 0.001
epochs = 75  # Number of epochs

# SGD training loop
for epoch in range(epochs):
    total_loss = 0
    for i in range(len(X)):
        # Select data point
        x_i = X[i].reshape(1, -1)
        y_i = Y[i].reshape(1, -1)

        # Forward pass
        Z1 = np.dot(x_i, W1) + b1
        A1 = linear(Z1)
        Z2 = np.dot(A1, W2) + b2
        A2 = linear(Z2)

        # Calculate loss (for this example)
        loss = mse_loss(y_i, A2)
        total_loss += loss

        # Compute gradients
        dA2 = 2 * (A2 - y_i)
        dW2 = np.dot(A1.T, dA2)
        db2 = np.sum(dA2, axis=0)

        dA1 = np.dot(dA2, W2.T)
        dW1 = np.dot(x_i.T, dA1)
        db1 = np.sum(dA1, axis=0)

        # Update weights and biases
        W2 -= learning_rate * dW2
        b2 -= learning_rate * db2
        W1 -= learning_rate * dW1
        b1 -= learning_rate * db1

    print(f"Epoch {epoch + 1}, Average Loss: {total_loss / len(X)}")

# Output final updated parameters
print("\nFinal Updated W1:")
print(W1)
print("Final Updated W2:")
print(W2)
print("Final Updated b1:")
print(b1)
print("Final Updated b2:")
print(b2)


Epoch 1, Average Loss: 26.345577666415263
Epoch 2, Average Loss: 19.85942891863526
Epoch 3, Average Loss: 10.881602572213675
Epoch 4, Average Loss: 3.777037799271362
Epoch 5, Average Loss: 1.223804496951285
Epoch 6, Average Loss: 0.886054487303891
Epoch 7, Average Loss: 0.9037980809999199
Epoch 8, Average Loss: 0.9126959329820745
Epoch 9, Average Loss: 0.902260700045425
Epoch 10, Average Loss: 0.8845704163881785
Epoch 11, Average Loss: 0.8648841635344682
Epoch 12, Average Loss: 0.8449243479934068
Epoch 13, Average Loss: 0.8252101002660123
Epoch 14, Average Loss: 0.8058875894164779
Epoch 15, Average Loss: 0.786990784041695
Epoch 16, Average Loss: 0.7685205480074296
Epoch 17, Average Loss: 0.7504683540826491
Epoch 18, Average Loss: 0.732823343635213
Epoch 19, Average Loss: 0.7155744024598001
Epoch 20, Average Loss: 0.6987107494353051
Epoch 21, Average Loss: 0.6822220834257697
Epoch 22, Average Loss: 0.6660986005295739
Epoch 23, Average Loss: 0.6503309746644773
Epoch 24, Average Loss: 0.6

## ## neutral network in regression Analysis using Keras

In [ ]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

# Create the DataFrame
df = pd.DataFrame({
    'cgpa': [8, 7, 6, 5],
    'profile_score': [8, 9, 10, 12],
    'lpa': [4, 5, 6, 7]
})

# Prepare input data (only the first two columns are features)
X = df[['cgpa', 'profile_score']].values
# Prepare output data
Y = df['lpa'].values

# Create the model
model = Sequential([
    Dense(2, input_dim=2, activation='linear'),  # Hidden layer with 2 neurons
    Dense(1, activation='linear')  # Output layer with 1 neuron
])

# Compile the model
model.compile(optimizer=Adam(learning_rate=0.001), loss='mean_squared_error')

# Train the model
history = model.fit(X, Y, epochs=75, batch_size=1, verbose=1)

# Print the weights and biases
weights, biases = model.layers[0].get_weights()
print("Weights of first layer (W1):", weights)
print("Biases of first layer (b1):", biases)

weights, biases = model.layers[1].get_weights()
print("Weights of second layer (W2):", weights)
print("Biases of second layer (b2):", biases)


Epoch 1/75
4/4 [==============================] - 0s 1ms/step - loss: 93.9473
Epoch 2/75
4/4 [==============================] - 0s 706us/step - loss: 90.5388
Epoch 3/75
4/4 [==============================] - 0s 632us/step - loss: 87.4362
Epoch 4/75
4/4 [==============================] - 0s 1ms/step - loss: 84.3271
Epoch 5/75
4/4 [==============================] - 0s 637us/step - loss: 81.0768
Epoch 6/75
4/4 [==============================] - 0s 692us/step - loss: 78.1189
Epoch 7/75
4/4 [==============================] - 0s 628us/step - loss: 75.4149
Epoch 8/75
4/4 [==============================] - 0s 617us/step - loss: 72.5830
Epoch 9/75
4/4 [==============================] - 0s 570us/step - loss: 69.6141
Epoch 10/75
4/4 [==============================] - 0s 731us/step - loss: 67.0954
Epoch 11/75
4/4 [==============================] - 0s 631us/step - loss: 64.4318
Epoch 12/75
4/4 [==============================] - 0s 646us/step - loss: 61.9686
Epoch 13/75
4/4 [========================